## Jobs to build and publish deb, rpm and arch based packages
include:
 - project: 'ProtonVPN/Linux/_gitlab-ci'
   ref: public-protonvpn-repo
   file: 'gitlab-ci-build-publish-debian.yml'
 - project: 'ProtonVPN/Linux/_gitlab-ci'
   ref: public-protonvpn-repo
   file: 'gitlab-ci-build-publish-rpm.yml'
 - project: 'ProtonVPN/Linux/_gitlab-ci'
   ref: public-protonvpn-repo
   file: 'gitlab-ci-build-publish-arch.yml'
 - project: 'agarroux/publish-github'
   ref: master
   file: '/jobs/release.gitlab-ci.yml'

default:
 image: $CI_REGISTRY_IMAGE:branch-$CI_COMMIT_REF_SLUG

stages:
 - image
 - test
 - build
 - publish
 - message
 - image-latest
 - release

variables:
  CI_REGISTRY_IMAGE_PROTON: "$CI_REGISTRY/infra/kubernetes/images"
  PKGNAME_ARCH: "python-proton-client"
  PKGNAME_RPM: "python3-proton-client"
  ORIGINAL_PKGNAME: "proton-python-client"


########## Manage the Image ##########
.common-image:
  image: $CI_REGISTRY/infra/kubernetes/images/docker:stable
  interruptible: true
  variables:
    DOCKER_HOST: tcp://docker:2375
  services:
    - name: $CI_REGISTRY/infra/kubernetes/images/docker:dind
      alias: docker
  before_script:
    - apk update
    - apk add make bash git gawk rsync


## Make image when we push to a branch -> run tests on top of this one
make-image-deb:
 stage: image
 extends: .common-image
 except:
   - schedules
   - triggers
 script:
   - make image-deb branch=$CI_COMMIT_REF_SLUG src=ubuntu
   
make-image-rpm:
 stage: image
 extends: make-image-deb
 script:
   - make image-rpm branch=$CI_COMMIT_REF_SLUG src=fedora
   
make-image-arch:
 stage: image
 extends: make-image-deb
 script:
   - make image-arch branch=$CI_COMMIT_REF_SLUG src=archlinux


######### CI Test Jobs ##########
test-deb:
 stage: test
 image: $CI_REGISTRY_IMAGE:branch-$CI_COMMIT_REF_SLUG-ubuntu
 interruptible: true
 needs:
   - job: make-image-deb
 script:
   - python3 -m pytest

test-rpm:
 extends: test-deb
 needs:
   - job: make-image-rpm
 image: $CI_REGISTRY_IMAGE:branch-$CI_COMMIT_REF_SLUG-fedora
 
test-arch:
 extends: test-deb
 needs:
   - job: make-image-arch
 image: $CI_REGISTRY_IMAGE:branch-$CI_COMMIT_REF_SLUG-archlinux


## Jobs to publish commits + tags from master to github
release-publish-github:
 stage: release
 needs:
   - job: build-deb
   - job: build-rpm
 when: manual
 variables:
   RELEASE_SYNC_PUBLIC_URL: git@github.com:ProtonMail/proton-python-client.git
   RELEASE_SYNC_TO_BRANCH: 'master'
   RELEASE_SYNC_FROM_BRANCH: 'master'
 extends: .release-sync-commit-shared

release-publish-github-tags:
 stage: release
 needs:
   - job: build-deb
   - job: build-rpm
 when: manual
 variables:
   RELEASE_SYNC_PUBLIC_URL: git@github.com:ProtonMail/proton-python-client.git
   RELEASE_SYNC_TO_BRANCH: 'master'
   RELEASE_SYNC_FROM_BRANCH: 'master'
 extends: .release-sync-tags-shared
